# permissions for end users to edit feeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feed-editor-role
rules:
- apiGroups:
  - putio.skynewz.dev
  resources:
  - feeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - putio.skynewz.dev
  resources:
  - feeds/status
  verbs:
  - get
