# permissions for end users to view feeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feed-viewer-role
rules:
- apiGroups:
  - skynewz.dev
  resources:
  - feeds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skynewz.dev
  resources:
  - feeds/status
  verbs:
  - get
