---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - putio.skynewz.dev
  resources:
  - feeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - putio.skynewz.dev
  resources:
  - feeds/finalizers
  verbs:
  - update
- apiGroups:
  - putio.skynewz.dev
  resources:
  - feeds/status
  verbs:
  - get
  - patch
  - update
