// Code generated by ifacemaker; DO NOT EDIT.

package putio

import (
	"context"
)

// RssService ...
type RssService interface {
	// List RSS feeds.
	List(ctx context.Context) ([]*Feed, error)
	// Get an RSS feed.
	Get(ctx context.Context, id uint) (*Feed, error)
	// Delete a RSS feed.
	Delete(ctx context.Context, id uint) error
	// Create an RSS feed.
	Create(ctx context.Context, feed *Feed) (*Feed, error)
	// Update an RSS feed.
	Update(ctx context.Context, feed *Feed, id uint) error
	// Pause given feed.
	Pause(ctx context.Context, id uint) error
	// Resume given feed.
	Resume(ctx context.Context, id uint) error
}
